### ISSUE TITLE
python-cssselect2 fails to build with Python 3.9.0a2.

### ISSUE THREAD

**Issue by FelixSchwarz** [Kozea/cssselect2#12]
python-cssselect2 fails to build with Python 3.9.0a2.

    _____________ ERROR collecting cssselect2/tests/test_cssselect2.py _____________
    cssselect2/tests/test_cssselect2.py:48: in <module>
        TEST_DOCUMENT = get_test_document()
    cssselect2/tests/test_cssselect2.py:31: in get_test_document
        parent = next(e for e in document.getiterator() if e.get('id') == 'root')
    E   AttributeError: 'ElementTree' object has no attribute 'getiterator'

See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"Methods getchildren() and getiterator() in the ElementTree module have been removed. They were deprecated in Python 3.2. Use functions list() and iter() instead. The xml.etree.cElementTree module has been removed." 

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1793518

**Comment by tirkarthi** [comment]
I will add a PR for this.
