### PR TITLE
Use elemene.iter instead of getiterator for Python 3.9 compatibility.

### LINKED ISSUE #12: python-cssselect2 fails to build with Python 3.9.0a2.
python-cssselect2 fails to build with Python 3.9.0a2.

    _____________ ERROR collecting cssselect2/tests/test_cssselect2.py _____________
    cssselect2/tests/test_cssselect2.py:48: in <module>
        TEST_DOCUMENT = get_test_document()
    cssselect2/tests/test_cssselect2.py:31: in get_test_document
        parent = next(e for e in document.getiterator() if e.get('id') == 'root')
    E   AttributeError: 'ElementTree' object has no attribute 'getiterator'

See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"Methods getchildren() and getiterator() in the ElementTree module have been removed. They were deprecated in Python 3.2. Use functions list() and iter() instead. The xml.etree.cElementTree module has been removed." 

Downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1793518

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #12

### CODE REVIEW

**Comment by liZe** [comment]
Thanks a lot!

**Comment by FelixSchwarz** [comment]
Also thank you - another step to ease Fedora's transition to Python 3.9 :-)

**Comment by liZe** [comment]
> Also thank you - another step to ease Fedora's transition to Python 3.9 :-)

:)

I’ll release a new version soon.

**Comment by tirkarthi** [comment]
Thanks for the review and merge :)

**Comment by FelixSchwarz** [comment]
Do you plan on publishing a new release with this fix soon-ish? In Fedora we're about to switch to Python 3.9 and it would be nice if cssselect2 works without extra patches. However we can carry extra patches if necessary.

**Comment by liZe** [comment]
> Do you plan on publishing a new release with this fix soon-ish? In Fedora we're about to switch to Python 3.9 and it would be nice if cssselect2 works without extra patches. However we can carry extra patches if necessary.

Version 0.3.0 has been released, sorry for the delay.

**Comment by FelixSchwarz** [comment]
Thank you very much :-)
